### ISSUE TITLE
demo下载视频oom了

### ISSUE THREAD

**Issue by lyawei** [huangdali/M3U8Manger#2]
11-25 15:01:59.270 5030-5296/com.hdl.m3u8demo E/AndroidRuntime: FATAL EXCEPTION: Thread-5
                                                                Process: com.hdl.m3u8demo, PID: 5030
                                                                java.lang.OutOfMemoryError: Failed to allocate a 1024 byte allocation with 9433776 free bytes and 8MB until OOM; failed due to fragmentation (required continguous free 8192 bytes for a new buffer where largest contiguous free 0 bytes)
                                                                    at java.lang.StringFactory.newStringFromChars(StringFactory.java:218)
                                                                    at java.io.BufferedReader.readLine(BufferedReader.java:367)
                                                                    at java.io.BufferedReader.readLine(BufferedReader.java:400)
                                                                    at com.hdl.m3u8.utils.MUtils.parseIndex(MUtils.java:46)
                                                                    at com.hdl.m3u8.M3U8InfoManger$2.run(M3U8InfoManger.java:62)

**Comment by huangdali** [comment]
不要使用demo来运行，自己新建一个工程用最新版依赖，demo是准备新加功能，还没完成哦
